
---
title: "01. Operadores com R | Google Data Analytics"
output:
  html_document:
    toc: true
---


```{r}
%md
# Operadores aritméticos
Os exemplos usados abaixo são baseados na criação de duas variáveis x e y. 
```


```{r}
# Atribui valores as variáveis.
x <- 2
y <- 5
```


```{r}
# Soma.
x + y
```


```{r}
# Subtraição.
x - y
```


```{r}
# Miltiplicação.
x * y
```


```{r}
# Divisão.
x / y
```


```{r}
# Módulos (retorna o restante após a divisão).
y %% x
```


```{r}
# Divisão inteira (retorna um valor inteiro após a divisão).
y%/% x
```


```{r}
# Exponenciação.
y ^ x
```


```{r}
%md
# Operadores relacionais ou de comparação 
```


```{r}
# Menor que.
x < y
```


```{r}
# Maior que.
x > y
```


```{r}
# Menor ou igual a.
x <= 2
```


```{r}
# Maior ou igual a.
y >= 10
```


```{r}
# Igual a.
y == 5
```


```{r}
# Diferente de.
x != 2
```


```{r}
%md
# Operadores lógicos
```


```{r}
# Atribui um novo valor a variável x.
x <- 10
```


```{r}
# Operador lógico AND (& ou &&).
x > 2 & x < 12
```


```{r}
# Operador lógico OR (| ou ||).
x > 2 | x < 8
```


```{r}
# O operador NOT (!) basicamente inverte o valor lógico.
!(x < 15)
```


```{r}
%md
# Operadores de atribuição
```


```{r}
# Atribuição à esquerda.
x <- 2
```


```{r}
# Atribuição à esquerda.
x <<- 7
```


```{r}
# Atribuição à esquerda.
x = 9
```


```{r}
# Atribuição à direita.
11 -> x
```


```{r}
# Atribuição à direita.
21 ->> x
```


```{r}
%md
# Informações adicinais
https://r-coder.com/operators-r/#Assignment_operators_in_R
```

